### ISSUE TITLE
Type errors with GCC 14.1

### ISSUE THREAD

**Issue by rossburton** [rrthomas/enchant#379] opened 2024-05-09 12:09 UTC
When building enchant2 with GCC 14.1:

```
api.vala:43:18: error: assignment to 'gchar **' {aka 'char **'} from incompatible pointer type 'const gchar * const*' {aka 'const char * const*'} [-Wincompatible-pointer-types]
```

**Comment by rrthomas** [comment] 2024-05-09 12:43
This is caused by a bug in some versions of `valac`. If you're building from Vala, install the latest stable release. If you're building from C, this bug should be fixed in Enchant 2.7.3.

**Closed as completed by rrthomas** 2024-05-09 12:43 UTC
